--!jinja
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE OR REPLACE SCHEMA CORTEX_AGENTS_DEMO.PRINTING_COMPANY;

CREATE OR REPLACE STAGE DOCUMENTS
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );
  
CREATE OR REPLACE STAGE SEMANTIC_MODELS
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

COPY FILES
  INTO @DOCUMENTS
  FROM @CORTEX_AGENTS_DEMO.PUBLIC.GITHUB_REPO_CORTEX_AGENTS_DEMO/branches/{{branch}}/use_cases/printing_company/documents/
  PATTERN='.*[.]pdf';
ALTER STAGE DOCUMENTS REFRESH;

COPY FILES
  INTO @SEMANTIC_MODELS
  FROM @CORTEX_AGENTS_DEMO.PUBLIC.GITHUB_REPO_CORTEX_AGENTS_DEMO/branches/{{branch}}/use_cases/printing_company/semantic_models/
  PATTERN='.*[.]yaml';
ALTER STAGE SEMANTIC_MODELS REFRESH;

CREATE OR REPLACE NOTEBOOK SETUP_AGENT_PRINTING_COMPANY 
    FROM '@CORTEX_AGENTS_DEMO.PUBLIC.GITHUB_REPO_CORTEX_AGENTS_DEMO/branches/{{branch}}/use_cases/printing_company' 
        MAIN_FILE = 'SETUP_AGENT_PRINTING_COMPANY.ipynb' 
        QUERY_WAREHOUSE = COMPUTE_WH;
ALTER NOTEBOOK SETUP_AGENT_PRINTING_COMPANY ADD LIVE VERSION FROM LAST;
{% if EXECUTE_NOTEBOOKS %}
EXECUTE NOTEBOOK SETUP_AGENT_PRINTING_COMPANY();