USE ROLE ACCOUNTADMIN;

-- Fetch most recent files from Github repository
ALTER GIT REPOSITORY GITHUB_REPO_CORTEX_AGENTS_DEMO FETCH;

-- Create stage for the Streamlit App
CREATE OR REPLACE STAGE STREAMLIT_APP
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = ( TYPE = 'SNOWFLAKE_FULL' );

-- Copy Streamlit App into to stage
COPY FILES
  INTO @STREAMLIT_APP
  FROM @CORTEX_AGENTS_DEMO.PUBLIC.GITHUB_REPO_CORTEX_AGENTS_DEMO/branches/main/agent_app/;
ALTER STAGE STREAMLIT_APP REFRESH;

-- Create Streamlit App
CREATE OR REPLACE STREAMLIT CORTEX_AGENT_CHAT_APP
    ROOT_LOCATION = '@CORTEX_AGENTS_DEMO.PUBLIC.STREAMLIT_APP'
    MAIN_FILE = '/app.py'
    QUERY_WAREHOUSE = COMPUTE_WH;